---

- name: install the latest version of packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - epel-release
    - centos-release-openstack-ocata
    - python-oslo-config
    - python-pip
    - python2-jinja2
  delegate_to: localhost
  run_once: True

- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - centos-release-openstack-ocata
    - python-pip
    - python2-jinja2
    - python-oslo-config

- name: Load ip_vs module
  modprobe:
    name: ip_vs
    state: present
